source 'https://rubygems.org'

group :development do

  # Sass, Compass and extensions.
  gem 'sass'                    # Sass.
  gem 'compass'                 # Framework built on Sass.
  gem 'susy'                    # Susy grid framework.
  gem 'singularitygs'           # Alternative to the Susy grid framework.
  gem 'toolkit'                 # Compass utility from the fabulous Snugug.
  gem 'breakpoint'              # Manages CSS media queries.
  gem 'sass-globbing'           # Allows you to import many sass or scss files
                                # in a single import statement.
end
